# Makefile generated by BNFC.

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestCPP

# Rules for building the parser.

ErrM.hs LexCPP.x PrintCPP.hs ParCPP.y TestCPP.hs : CPP.cf
	bnfc --haskell CPP.cf

%.hs : %.y
	happy --ghc --coerce --array --info $<

%.hs : %.x
	alex --ghc $<

TestCPP : TestCPP.hs ErrM.hs LexCPP.hs ParCPP.hs PrintCPP.hs
	ghc --make $< -o $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsCPP.hs AbsCPP.hs.bak ComposOp.hs ComposOp.hs.bak DocCPP.txt DocCPP.txt.bak ErrM.hs ErrM.hs.bak LayoutCPP.hs LayoutCPP.hs.bak LexCPP.x LexCPP.x.bak ParCPP.y ParCPP.y.bak PrintCPP.hs PrintCPP.hs.bak SharedString.hs SharedString.hs.bak SkelCPP.hs SkelCPP.hs.bak TestCPP.hs TestCPP.hs.bak XMLCPP.hs XMLCPP.hs.bak ASTCPP.agda ASTCPP.agda.bak ParserCPP.agda ParserCPP.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak CPP.dtd CPP.dtd.bak TestCPP LexCPP.hs ParCPP.hs ParCPP.info ParDataCPP.hs Makefile


# EOF
